### ISSUE TITLE
Seeing 0 damage weapons for all AT KT weapons

### ISSUE THREAD

**Issue by kennnyolo** [jasonycw/MHW-Kulve-Taroth-Droprate-Editor#5]
Hey, sorry I installed your mod and applied 100% on ATKT for every tier but all I see is 0 value weapons that are all tier 1. I saw it in the nexusmod comments but no one else followed up on it. I have light pillar and cute handler face. Used to have ATKT craftable weapon but uninstalled it by deleting the files as per instructions. Still, it is showing the same problem. Any ideas why it would cause such problem ?!

**Comment by jasonycw** [comment]
Would you mind uploading the `em117_ex_grade_lot.em117glt` file to here?
Since this tool only create the mod droprate file from [Asterisk's Modified ATKT Drop Rate](https://www.nexusmods.com/monsterhunterworld/mods/1010?tab=files)

This one is the one I have created back in April: [em117_ex_grade_lot.zip](https://github.com/jasonycw/MHW-Kulve-Taroth-Droprate-Editor/files/3512816/em117_ex_grade_lot.zip)
Using the following setting
![image](https://user-images.githubusercontent.com/4518597/63221981-d65a1980-c1d3-11e9-9168-ee652eca5ab5.png)
I double check the mod file with the latest one from Asterisk's, and I see no changes

Maybe recent update has changed the table setting again to ready for Iceborn, I am not sure, since I haven't done ATKT run for months.
You can also try [Asterisk's Modified ATKT Drop Rate](https://www.nexusmods.com/monsterhunterworld/mods/1010?tab=files) and see if it is still working
If it also creates R1 white weapons, you may also need to file a bug report [here](https://www.nexusmods.com/monsterhunterworld/mods/1010?tab=bugs)

Edit: Just tested 1 ATKT run with the above mod file and can properly get KT weapon drops, would you mind double check if there is any other mod that alter the weapons?

**Comment by kennnyolo** [comment]
hey thx for such prompt reply. I tried to attach file here but it says it does not support this file type on this. I simply switched every tier to 100% Kjar but ended up getting all 0 value weapons. I have done Asterisk's format, where the R6-R8 shows normal but still rainbow drops are all 0 value.

**Comment by kennnyolo** [comment]
Please note that I have used this drop rate editor before without the Kjar update. For some reason when I try now it does not work. If you want maybe I can somehow send it to your email or other channels to take a look ? Thanks !

**Comment by jasonycw** [comment]
You can just zip the mod file and upload here, the above file is zipped. 
Can you try that mod file and see if you get Kjar weapons?

Which version have you use? 
Is it `v2.1`? The tool is updated after ATKT is released.

What is the name for that mod file? 
Is it `em117_ex_grade_lot.em117glt`? This is AT KT droptable
Not `em117_grade_lot.em117glt`? This is non-AT KT droptable
If you still got `em117_grade_lot.em117glt` in that folder, please remove it and just leave `em117_ex_grade_lot.em117glt` there

If you are using v2.1 to create `em117_ex_grade_lot.em117glt` and do not have  `em117_grade_lot.em117glt`, than I strongly suspect it is due to some other weapon mod that is not removed completely. 
You can try rename `nativePC` to `nativePC_backup` and put only the drop table mod in a new `nativePC` folder and try if this will work.

**Comment by kennnyolo** [comment]
hey there, I checked my file vs yours "all 100%", it's the exact same. Yet I have same problem. I also just downloaded and tried  Asterisk's Modified ATKT Drop Rate. Same thing. 
![yo1](https://user-images.githubusercontent.com/54228213/63311144-32ec3000-c2cb-11e9-9575-051d8dc614fb.png)
![yo2](https://user-images.githubusercontent.com/54228213/63311153-3aabd480-c2cb-11e9-8a6d-3dc85b6ce31e.png)

**Comment by kennnyolo** [comment]
Very strange, you can see it has no name, 0 damage, no descriptions and Rare 1.

Maybe I should just try to delete and reinstall the entire game ?

**Comment by jasonycw** [comment]
I do think it is either some other mod(can be even some skin mod) breaking the weapons stat or the game file is corrupted.

Try remove the `nativePC` and see if things work properly, if not, check the files or reinstall the game maybe helpful?

**Comment by kennnyolo** [comment]
Hey hey. I removed nativePC and re-installed the entire game. It does work perfectly now. I'm not even sure which mod was affecting it but I guess I would figure that part out myself. Thanks for your help here ! Back to hunting :P

**Comment by jasonycw** [comment]
![image](https://user-images.githubusercontent.com/4518597/63409600-0ef03200-c424-11e9-8d05-c224b2108a49.png)
